### ISSUE TITLE
Support recent kernels (>= 5.10)

### ISSUE THREAD

**Issue by jeffwilde** [danielfullmer/nixos-nvidia-vgpu#4]
Thanks for packaging this up! I have been interested in trying this since I first heard about the hack.

Unfortunately, I came across some compilation errors, possibly due to kernel version mismatch? I ​wasn't able to immediately figure it out, so I thought I would share here 

I'm building via a NixOS flake build of nixos-unstable:
```
build/kernel/nvidia/nv-vgpu-vmbus.c: In function 'nv_vmbus_open':
/build/kernel/nvidia/nv-vgpu-vmbus.c:911:55: error: 'struct vmbus_channel' has no member named 'target_vp'; did you mean 'target_cpu'?
  911 |     open_msg.target_vp = nv_hyperv_ctx.guest_channel->target_vp;
      |                                                       ^~~~~~~~~
      |                                                       target_cpu
/build/kernel/nvidia/nv-vgpu-vmbus.c: In function 'nv_vmbus_setup':
/build/kernel/nvidia/nv-vgpu-vmbus.c:1272:68: error: 'PAGE_KERNEL_RX' undeclared (first use in this function); did you mean 'PAGE_KERNEL_ROX'?
 1272 |     nv_hyperv_ctx.nv_hypercall_pg = vmap(&page, num_pages, VM_MAP, PAGE_KERNEL_RX);
      |                                                                    ^~~~~~~~~~~~~~
      |                                                                    PAGE_KERNEL_ROX
/build/kernel/nvidia/nv-vgpu-vmbus.c:1272:68: note: each undeclared identifier is reported only once for each function it appears in
/build/kernel/nvidia/nv-caps.c: In function 'nv_cap_close_fd':
/build/kernel/nvidia/nv-caps.c:592:5: error: implicit declaration of function 'sys_close' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.>
  592 |     sys_close(fd);
      |     ^~~~~~~~~
```

The failures are all undefined symbols. The `sys_close` failure especially made me think of a kernel version mismatch. I later found [this discussion](https://bbs.archlinux.org/viewtopic.php?pid=1948516#p1948516) of what looks like the same problem. 

This may also be influenced by other Nvidia-related NixOS configuration options. I'm happy to share my settings for those here as well, if useful.

Full build log: [1f09h5bw0sq4ndwwnsj51c69cr2sik3l-nvidia-x11-460.73.01-5.11.14.drv.log](https://github.com/danielfullmer/nixos-nvidia-vgpu/files/6370308/1f09h5bw0sq4ndwwnsj51c69cr2sik3l-nvidia-x11-460.73.01-5.11.14.drv.log)

**Comment by danielfullmer** [comment]
IIRC, the KVM + GRID drivers we're using don't compile with kernels `>= 5.10`.  I'm currently using `5.4`.  There's a WIP patch for more recent kernels [here](https://github.com/DualCoder/vgpu_unlock/pull/34), but I don't think it's ready yet.

**Comment by jeffwilde** [comment]
Aha, I missed that PR on the upstream repo. Thx for the link.

I will try again against an older kernel. I hadn't thought of that since the consumer drivers work fine against newer kernels.

**Comment by PythonNut** [comment]
There is a related repo for kernel 5.12: https://github.com/rupansh/vgpu_unlock_5.12
